### PR TITLE
fix(ci): fix problems of CI

### PR DESCRIPTION
**Pull request by liubog2008**
**What this PR does**
1. add gometalinter config
2. delete get-started example
3. add crud.go to curd package to pass goveralls

**why we need it**

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by liubog2008** [comment]
ok to test

**Comment by liubog2008** [comment]
@Jimexist

**Comment by liubog2008** [comment]
@ddysher ?

**Comment by ddysher** [comment]
@liubog2008  I think you also need to update README.

**Pull request merged**
