### PR TITLE
chore(linter): add gometalinter config

### PR DESCRIPTION
**Pull request by liubog2008**
**What this PR does**

**why we need it**

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Jimexist** [comment]
@liubog2008 need to fix vendor

**Comment by liubog2008** [comment]
I fixed in #19 = =

**Comment by ddysher** [comment]
@liubog2008 what's the status?

**Comment by liubog2008** [comment]
@ddysher I'll fix the problem this week. `goveralls` can't skip the package

**Comment by ddysher** [comment]
@liubog2008 LGTM

**Comment by liubog2008** [comment]
see #20

**Pull request closed without merging**
