### PR TITLE
chore(linter): delete gas from linter

### PR DESCRIPTION
**Pull request by liubog2008**
**What this PR does / why we need it**:

delete gas linter

**Which issue(s) this PR is related to** *(optional, link to 3rd issue(s))*:

Fixes #

Reference to #

**Special notes for your reviewer**:

/cc @ddysher 

**Release note**:

```release-note
1. delete gas from linters
```

### CODE REVIEW

**Comment by ddysher** [comment]
add rational for ur change

**Comment by liubog2008** [comment]
gas has been deleted by gometalinter...

**Pull request merged**
